# Generated by Django 5.2 on 2025-04-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('seed', models.CharField(max_length=64, unique=True)),
                ('terrain', models.CharField(choices=[('rocky', 'Rocky'), ('icy', 'Icy'), ('gaseous', 'Gaseous'), ('desert', 'Desert'), ('jungle', 'Jungle')], max_length=20)),
                ('atmosphere_color', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
