# Generated by Django 5.1.2 on 2025-05-07 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='planet',
            name='liquid_color',
            field=models.CharField(default='#1E90FF', help_text='HEX color code for the liquid (e.g., #1E90FF)', max_length=7),
        ),
        migrations.AddField(
            model_name='planet',
            name='liquid_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text="Percentage of the planet's surface covered by liquid (0-100)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
