# Generated by Django 5.1.2 on 2025-05-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_alter_planet_options_planet_liquid_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='land_color',
            field=models.CharField(default='#1E90FF', help_text='HEX color code for the liquid (e.g., #1E90FF)', max_length=7),
        ),
    ]
